### PR TITLE
Bump GNOME Runtime to 3.30

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by Hjdskes** [comment]
Thanks, I haven't had the time to do this myself yet. Have you tested if everything works?

**Comment by bilelmoussaoui** [comment]
You can run a test build using `bot, build`. Just write it as a comment here.

**Comment by TingPing** [comment]
ofc that only ensures it builds not works.

**Comment by bilelmoussaoui** [comment]
@TingPing Already tried it before submitting the PR :) was just talking about whether it builds on all the platforms or not

**Comment by bilelmoussaoui** [comment]
Any news?

**Comment by Hjdskes** [comment]
Sorry, I am incredibly busy with the last touches on my thesis paper due tomorrow. I might have time to test this in the weekend.

**Comment by bilelmoussaoui** [comment]
Good luck with that!!!

**Comment by Hjdskes** [comment]
I just verified that it works. Thanks again for the pull request and apologies for taking so long to get around to it (I graduated, so that's something to show for it at least :smile:).

**Pull request merged**
